# NGINX Reverse Proxy configuration for Interra Push Server

server {
    listen 80;
    server_name push.interra.ru localhost;

    # Gzip сжатие для быстрого ответа клиентам
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000;

    location / {
        proxy_pass http://push-server:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    # Отключаем логирование для логов favicon
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }
}
